version: '3.8'

services:
  emoji-app:
    image: emoji-app:latest
    container_name: emoji-app-container
    ports:
      - "4646:4646"  # Sol taraf: Senin bilgisayarın, Sağ taraf: Konteynerin içi
    restart: always
